<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <OutputType>WinExe</OutputType>
        <TargetFramework>net8.0-windows</TargetFramework>
        <Nullable>enable</Nullable>
        <BuiltInComInteropSupport>true</BuiltInComInteropSupport>
        <ApplicationManifest>app.manifest</ApplicationManifest>
        <AvaloniaUseCompiledBindingsByDefault>true</AvaloniaUseCompiledBindingsByDefault>
        <UseWindowsForms>true</UseWindowsForms>
    </PropertyGroup>


    <ItemGroup>
        <PackageReference Include="Avalonia" Version="11.2.1" />
        <PackageReference Include="Avalonia.Controls.ItemsRepeater" Version="11.1.5" />
        <PackageReference Include="Avalonia.Desktop" Version="11.2.1"/>
        <PackageReference Include="Avalonia.ReactiveUI" Version="11.2.1" />
        <PackageReference Include="Avalonia.Themes.Fluent" Version="11.2.1" />
        <PackageReference Include="Avalonia.Fonts.Inter" Version="11.2.1"/>
        <!--Condition below is needed to remove Avalonia.Diagnostics package from build output in Release configuration.-->
        <PackageReference Condition="'$(Configuration)' == 'Debug'" Include="Avalonia.Diagnostics" Version="11.2.1"/>
        <PackageReference Include="Avalonia.Themes.Simple" Version="11.2.1" />
        <PackageReference Include="H.InputSimulator" Version="1.4.2" />
        <PackageReference Include="Makaretu.Dns.Multicast" Version="0.27.0" />
        <PackageReference Include="Material.Icons.Avalonia" Version="2.1.10" />
        <PackageReference Include="NetOfficeFw.PowerPoint" Version="2.0.0-preview20" />
        <PackageReference Include="System.Management" Version="8.0.0" />
        <PackageReference Include="Websocket.Client" Version="5.1.2" />
        <PackageReference Include="YamlDotNet" Version="16.1.2" />
    </ItemGroup>


    <ItemGroup>
      <ProjectReference Include="..\ClickerFixer.Data\ClickerFixer.Data.csproj" />
    </ItemGroup>


    <ItemGroup>
      <AdditionalFiles Include="UI\RippleEffect\Theme.axaml" />
    </ItemGroup>


    <ItemGroup>
      <None Remove="Resources\tray_default.png" />
      <AvaloniaResource Include="Resources\tray_default.png" />
    </ItemGroup>
</Project>
